name = "SteadyWaves"
uuid = "2d4f3d31-6681-40b2-b238-b8279529db51"
authors = ["Maciej Paprota"]
version = "1.1.1"

[deps]
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[compat]
NonlinearSolve = "3, 4"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
examples = ["CairoMakie"]
test = ["Test"]
