name = "SteadyWaves"
uuid = "2d4f3d31-6681-40b2-b238-b8279529db51"
authors = ["Maciej Paprota"]
version = "1.0.0-DEV"

[deps]
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
